import Head from 'next/head'
import Layout from "../../../components/Layout"
import { useRouter } from 'next/router'

const Index = () => {
    const router = useRouter()
    const { id } = router.query
    return (

        <Layout>
            <Head>
                <title>News - Residences Sindhorn Kempinski</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="h-full w-full relative flex justify-center">
                <div className="w-full h-full bg-white md:rounded-tr-[100px]  max-w-7xl  py-10 relative ">
                    <div className="absolute -top-5 -left-8  hidden md:block z-10">
                        <img src="http://upload.wikimedia.org/wikipedia/en/e/ec/Soccer_ball.svg" alt="ball" className="w-24 h-24 roll" />
                    </div>
                    <section className="flex w-full flex-col justify-center items-center px-4 lg:px-10">
                        <p className="text-3xl font-medium">Polo Corner</p>
                        <div className='flex items-end w-auto md:w-[736px] flex-col'>
                            <button onClick={() => router.back()} className='rounded-none bg-transparent border-2 border-[#B6A694] w-[120px] h-[30px] text-[#B6A694] inline-flex items-center justify-center'>
                                <svg className="w-5 h-5 mr-2 -ml-1 rotate-180" aria-hidden="true" focusable="false" data-prefix="fab" data-icon="apple" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 512"><path fill="currentColor" d="M64 448c-8.188 0-16.38-3.125-22.62-9.375c-12.5-12.5-12.5-32.75 0-45.25L178.8 256L41.38 118.6c-12.5-12.5-12.5-32.75 0-45.25s32.75-12.5 45.25 0l160 160c12.5 12.5 12.5 32.75 0 45.25l-160 160C80.38 444.9 72.19 448 64 448z" /></svg>
                                Back
                            </button>

                        </div>
                    </section>

                </div>



            </div>
        </Layout>
    );
}

export default Index;