
import Head from "next/head";
import Layout from "../components/Layout";
import Link from 'next/link';
import React, { useState, useEffect } from "react";
import { useRouter } from "next/router";
import '@fancyapps/ui/dist/carousel.css';

const About = () => {

    return (
        <Layout>
            <Head>
                <title>About - Polo Football Park</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="h-full w-full relative flex justify-center">
                <div className="w-full h-full bg-white md:rounded-tr-[100px]  max-w-7xl  py-10 relative ">
                    <div className="absolute -top-5 -left-8  hidden md:block z-10">
                        <img src="http://upload.wikimedia.org/wikipedia/en/e/ec/Soccer_ball.svg" alt="ball" className="w-24 h-24 roll" />
                    </div>

                    <div className="mt-10 w-full h-full grid grid-cols-1 sm:grid-cols-2 gap-3 p-5">
                        <div className="text-center sm:text-right row-start-2 flex h-full items-center md:mx-10 ">
                            Siam Sindhorn Co.,Ltd  Is The Developer at POLO Football Park project. There are 4 soccer fields with high quality artificial turf. The field dimensions are 25m. wide and 42m long. You can visit us by 2 ways from RAMA IV road or Wireless road.
                        </div>
                        <div className="row-start-1 sm:row-start-2 md:mr-10">
                            <img src="https://polofootballpark.com//images/gallery/2a3edc4ed681a421c845f6f612906ee8__2630f05a48843b1e62afded3c01cd198-1458615947.jpg" alt="logo" className="h-full w-full object-contain object-center shadow-md " />
                        </div>
                    </div>

                    <div className="mt-10 w-full h-full flex flex-col justify-center items-center">
                        <p className="text-3xl font-semibold">Facilities</p>
                        <p className="w-full lg:w-1/2 text-center px-5">Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus, laborum quo. Harum corporis laboriosam explicabo deserunt voluptates vitae, neque provident.</p>
                        <div className="w-full grid grid-cols-2 md:grid-cols-4 gap-3 p-10 ">
                            <div className="h-48 shadow-sm flex flex-col justify-center">
                                <img src="https://polofootballpark.com/images/icon/1.png" alt="facilities" className="h-2/3 object-contain object-center" />
                                <p className="text-center">	Soccer field for playing football.</p>
                            </div>
                            <div className="h-48 shadow-sm flex flex-col justify-center">
                                <img src="https://polofootballpark.com/images/icon/2.png" alt="facilities" className="h-2/3 object-contain object-center" />
                                <p className="text-center">Rent for Soccer tournament or competition.</p>
                            </div>
                            <div className="h-48 shadow-sm flex flex-col justify-center">
                                <img src="https://polofootballpark.com/images/icon/10.png" alt="facilities" className="h-2/3 object-contain object-center" />
                                <p className="text-center">Rent for Advertisement.</p>
                            </div>
                            <div className="h-48 shadow-sm flex flex-col justify-center">
                                <img src="https://polofootballpark.com/images/icon/3.png" alt="facilities" className="h-2/3 object-contain object-center" />
                                <p className="text-center">	Rent for Events or Activities.</p>
                            </div>
                            <div className="h-48 shadow-sm flex flex-col justify-center">
                                <img src="https://polofootballpark.com/images/icon/4.png" alt="facilities" className="h-2/3 object-contain object-center" />
                                <p className="text-center">	Referee.</p>
                            </div>
                            <div className="h-48 shadow-sm flex flex-col justify-center">
                                <img src="https://polofootballpark.com/images/icon/5.png" alt="facilities" className="h-2/3 object-contain object-center" />
                                <p className="text-center">	Borrow football for playing.</p>
                            </div>
                            <div className="h-48 shadow-sm flex flex-col justify-center">
                                <img src="https://polofootballpark.com/images/icon/11.png" alt="facilities" className="h-2/3 object-contain object-center" />
                                <p className="text-center">	Vest service a divided team.</p>
                            </div>
                            <div className="h-48 shadow-sm flex flex-col justify-center">
                                <img src="https://polofootballpark.com/images/icon/6.png" alt="facilities" className="h-2/3 object-contain object-center" />
                                <p className="text-center">	Lockers and Towels.</p>
                            </div>
                            <div className="h-48 shadow-sm flex flex-col justify-center">
                                <img src="https://polofootballpark.com/images/icon/7.png" alt="facilities" className="h-2/3 object-contain object-center" />
                                <p className="text-center">		Bathroom with soap & shampoo.</p>
                            </div>
                            <div className="h-48 shadow-sm flex flex-col justify-center">
                                <img src="https://polofootballpark.com/images/icon/8.png" alt="facilities" className="h-2/3 object-contain object-center" />
                                <p className="text-center">	Food and Beverages.</p>
                            </div>
                            <div className="h-48 shadow-sm flex flex-col justify-center">
                                <img src="https://polofootballpark.com/images/icon/9.png" alt="facilities" className="h-2/3 object-contain object-center" />
                                <p className="text-center">		Free Wi-fi.</p>
                            </div>

                        </div>
                    </div>
                    <div className="mt-10 w-full h-full flex flex-col justify-center items-center">
                        <p className="text-3xl font-semibold">Regulations</p>
                        <p className="w-full lg:w-1/2 text-center px-5">Im order to play football with fun. please follow our instructions as follows.</p>
                        <div className="w-full grid grid-cols-2 md:grid-cols-4 gap-3 p-10 ">
                            <div className="h-48 shadow-sm flex flex-col justify-center">
                                <img src="https://polofootballpark.com/images/icon/r1.png" alt="facilities" className="h-2/3 object-contain object-center" />
                                <p className="text-center">Keep all area clean.</p>
                            </div>
                            <div className="h-48 shadow-sm flex flex-col justify-center">
                                <img src="https://polofootballpark.com/images/icon/r2.png" alt="facilities" className="h-2/3 object-contain object-center" />
                                <p className="text-center">No!. metal stud or high heel shoes.</p>
                            </div>
                            <div className="h-48 shadow-sm flex flex-col justify-center">
                                <img src="https://polofootballpark.com/images/icon/r3.png" alt="facilities" className="h-2/3 object-contain object-center" />
                                <p className="text-center">Dress sportswear properly.</p>
                            </div>
                            <div className="h-48 shadow-sm flex flex-col justify-center">
                                <img src="https://polofootballpark.com/images/icon/r4.png" alt="facilities" className="h-2/3 object-contain object-center" />
                                <p className="text-center">No!.Smoking in the soccer pitch.</p>
                            </div>
                            <div className="h-48 shadow-sm flex flex-col justify-center">
                                <img src="https://polofootballpark.com/images/icon/r5.png" alt="facilities" className="h-2/3 object-contain object-center" />
                                <p className="text-center">No!. Quarrel.</p>
                            </div>
                            <div className="h-48 shadow-sm flex flex-col justify-center">
                                <img src="https://polofootballpark.com/images/icon/r6.png" alt="facilities" className="h-2/3 object-contain object-center" />
                                <p className="text-center">Im case of quarrel., POLO Football Park has the right to stop playing football immediately.</p>
                            </div>
                            <div className="h-48 shadow-sm flex flex-col justify-center">
                                <img src="https://polofootballpark.com/images/icon/r7.png" alt="facilities" className="h-2/3 object-contain object-center" />
                                <p className="text-center">No!. Guns or Arms.</p>
                            </div>
                            <div className="h-48 shadow-sm flex flex-col justify-center">
                                <img src="https://polofootballpark.com/images/icon/r8.png" alt="facilities" className="h-2/3 object-contain object-center" />
                                <p className="text-center">	No!. Drugs.</p>
                            </div>
                            <div className="h-48 shadow-sm flex flex-col justify-center">
                                <img src="https://polofootballpark.com/images/icon/r9.png" alt="facilities" className="h-2/3 object-contain object-center" />
                                <p className="text-center">No!. Animals.</p>
                            </div>
                            <div className="h-48 shadow-sm flex flex-col justify-center">
                                <img src="https://polofootballpark.com/images/icon/r10.png" alt="facilities" className="h-2/3 object-contain object-center" />
                                <p className="text-center">No!. Gambling.</p>
                            </div>
                            <div className="h-48 shadow-sm flex flex-col justify-center">
                                <img src="https://polofootballpark.com/images/icon/r11.png" alt="facilities" className="h-2/3 object-contain object-center" />
                                <p className="text-center">	Please keep your belongings carefully. POLO Football Park has no responsibility for your loss.</p>
                            </div>

                        </div>
                    </div>

                </div>



            </div>
        </Layout>
    );
}

export default About;