
import Head from "next/head";
import Layout from "../components/Layout";
import Link from 'next/link';
import React, { useState, useEffect } from "react";
import { useRouter } from "next/router";
import '@fancyapps/ui/dist/carousel.css';
import en from '../locales/en'
import th from '../locales/th'

const About = () => {
    const router = useRouter();
    const { locale } = router;
    const t = locale === 'en' ? en : th;

    const changeLanguage = (e) => {
        const locale = e.target.value;
        router.push(router.pathname, router.asPath, { locale });
    };
    return (
        <Layout>
            <Head>
                <title>About - Polo Football Park</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="h-full w-full relative flex justify-center">
                <div className="w-full h-full bg-white md:rounded-tr-[100px]  max-w-7xl  py-10 relative ">
                    <div className="absolute -top-5 -left-8  hidden md:block z-10">
                        <img src="http://upload.wikimedia.org/wikipedia/en/e/ec/Soccer_ball.svg" alt="ball" className="w-24 h-24 roll" />
                    </div>
                    <div className="flex w-full flex-col justify-center items-center px-4 lg:px-10">
                        <p className="text-3xl font-medium md:hidden">
                            {locale === "en" ? "About us" : "เกี่ยวกับเรา"}
                        </p>
                        <div className="w-full h-full grid grid-cols-1 sm:grid-cols-2 gap-3 p-5">

                            <div className=" md:mr-10">
                                <img src={t.aboutus.image} alt="aboutus" className="h-full w-full object-contain object-center shadow-md rounded " />
                            </div>
                            <div className="flex h-full items-center md:mx-10 font-light text-base sm:text-lg">
                                {t.aboutus.about}
                            </div>
                        </div>

                        <div className="mt-10 w-full h-full flex flex-col justify-center items-center">
                            <p className="text-3xl font-medium mb-4">
                                {locale === "en" ? "Facilities" : "สิ่งอำนวยความสะดวก"}
                            </p>

                            <div className="w-full grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-3 ">
                                {t.aboutus.facilities.map((item, index) => (
                                    <div key={index} className="h-48 shadow-sm flex flex-col" >
                                        <img src={item.src} alt="facilities" className="h-28 object-contain object-top" />
                                        <p className="text-center font-light text-sm sm:text-base">{item.description}</p>
                                    </div>
                                ))

                                }

                            </div>
                        </div>
                        <div className="mt-10 w-full h-full flex flex-col justify-center items-center mb-4">
                            <p className="text-3xl font-medium ">
                                {locale === "en" ? "Regulations" : "ระเบียบการใช้งานสนาม"}
                            </p>
                            <p className="w-full lg:w-1/2 text-center px-5 font-light mb-4">
                                {locale === "en" ? "Im order to play football with fun. please follow our instructions as follows." : "เพื่อความเป็นระเบียบเรียบร้อยในสนาม ขอความร่วมมือจากผู้มาใช้บริการปฏิบัติตามกฎต่างๆ ดังต่อไปนี้"}
                            </p>

                            <div className="w-full grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-3 ">
                                {t.aboutus.regulations.map((item, index) => (
                                    <div key={index} className="max-h-72 shadow-sm flex flex-col p-2" >
                                        <img src={item.src} alt="facilities" className="h-28 object-contain object-top" />
                                        <p className="text-center font-light text-sm sm:text-base">{item.description}</p>
                                    </div>
                                ))

                                }

                            </div>
                        </div>
                    </div>


                </div>



            </div>
        </Layout>
    );
}

export default About;