import Head from "next/head";
import Layout from "../components/Layout";
import Link from 'next/link';
import React, { useState, useEffect } from "react";
import { useRouter } from "next/router";
import '@fancyapps/ui/dist/carousel.css';

const Booking = () => {

    return (
        <Layout>
            <Head>
                <title>Booking - Polo Football Park</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="h-full w-full relative flex justify-center">
                <div className="w-full h-full bg-white md:rounded-tr-[100px]  max-w-7xl  py-10 relative ">
                    <div className="absolute -top-5 -left-8  hidden md:block z-10">
                        <img src="http://upload.wikimedia.org/wikipedia/en/e/ec/Soccer_ball.svg" alt="ball" className="w-24 h-24 roll" />
                    </div>
                    <section className="flex w-full flex-col justify-center items-center px-4 lg:px-10">
                        <p className="text-3xl font-medium">Rate&Booking</p>

                        <div className="grid grid-cols-1 sm:grid-cols-6 gap-3 w-full h-full mt-10">
                            <div className="sm:col-span-4 overflow-hidden">
                                <p>Please select date to check </p>
                                <select name="datepick" id="date" className="w-full border-2 mb-4" defaultValue="value"></select>
                                <img src="/assets/table.jpeg" alt="xxxx" className="object-cover w-full h-full object-center" />
                            </div>
                            <div className="sm:col-span-2 ">

                                <div className="my-5 flex gap-3 w-full">

                                    <button className="bg-red-400 p-3 w-36"> จองแล้ว </button>


                                    <button className="bg-green-400 p-3 w-36 "> ว่าง </button>
                                </div>
                                <p className="text-red-400">*** Status Table reservations are just booking information field. . At the current time Changes can not be adjusted, and reserves the right to change. If you have any questions, please contact us.</p>



                                <div className="w-full h-96 bg-blue-100 flex justify-center items-center my-5">
                                    Rate
                                </div>

                                <div className="w-full h-48 bg-yellow-200 flex justify-center items-center my-5">
                                    For more information
                                </div>

                            </div>


                        </div>



                    </section>

                </div>



            </div>
        </Layout>
    );
}

export default Booking;