import Head from "next/head";
import Layout from "../components/Layout";
import Link from 'next/link';
import React, { useState, useEffect } from "react";
import { useRouter } from "next/router";
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faCar, faTrain } from '@fortawesome/free-solid-svg-icons'

const Contact = () => {
    return (
        <Layout>
            <Head>
                <title>Contact - Polo Football Park</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="h-full w-full flex justify-center relative ">

                <div className="w-full h-full bg-white md:rounded-tr-[100px]  max-w-7xl  py-10 relative ">
                    <div className="absolute -top-5 -left-8  hidden md:block z-10">
                        <img src="http://upload.wikimedia.org/wikipedia/en/e/ec/Soccer_ball.svg" alt="ball" className="w-24 h-24 roll" />
                    </div>
                    {/* Heading */}
                    <section className="flex w-full flex-col justify-center items-center px-4 lg:px-10">
                        <p className="text-3xl font-medium">Contact</p>
                        <p>Get in touch with us!</p>


                        <div className="py-10 grid grid-cols-1 md:grid-cols-6 gap-3 w-full  ">
                            <div className=" grid grid-cols-3 md:grid-cols-1 w-full items-center justify-items-center lg:p-8 shadow-sm md:col-span-2 min-h-[150px]">

                                <FontAwesomeIcon icon={faCar} className="w-16 h-16 " />
                                <div className="col-span-2 md:col-span-1">

                                    จาก สวนลุมพินี ถนนพระราม 4 ข้ามสะพาน ไทยเบลเยียม เมื่อลงสะพานชิดซ้ายประมาณ 200 เมตร เลี้ยวซ้ายเข้าซอยปลูกจิต ตรงไปตามทางจนเจอสี่แยก เลี้ยวซ้าย ตรงเข้าไป สนามฟุตบอลจะอยู่ทางขวามือ
                                </div>
                            </div>
                            <div className=" grid grid-cols-3 md:grid-cols-1 w-full items-center justify-items-center lg:p-8 shadow-sm md:col-span-2 min-h-[150px]">
                                <FontAwesomeIcon icon={faCar} className="w-16 h-16 " />
                                <div className="col-span-2 md:col-span-1">

                                    จาก สี่แยกเพลินจิต ตรงเข้ามามุ่งหน้ามาทางสวนลุมพินี ผ่าน สามแยกถนนวิทยุตัดถนนสารสิน แล้ววิ่งชิดเลนซ้าย ประมาณ 200 เมตร วิ่งตรงเข้ามาจะเห็น RBSC Polo Club เลี้ยวซ้ายตามแนวกำแพง เจอสามแยกเลี้ยวขวา จากนั้นตรงไปสนามฟุตบอลจะอยู่ทางซ้ายมือ
                                </div>
                            </div>
                            <div className=" grid grid-cols-3 md:grid-cols-1 w-full items-center justify-items-center lg:p-8 shadow-sm md:col-span-2 min-h-[150px]">
                                <FontAwesomeIcon icon={faCar} className="w-16 h-16 " />
                                <div className="col-span-2 md:col-span-1">

                                    จาก เซ็นทรัลชิดลม ตรงเข้ามาผ่านถนนหลังสวน เจอสามแยก เลี้ยวซ้าย วิ่งตรงเข้ามา จนเจอสามแยก เลี้ยวขวาเข้าถนนวิทยุ วิ่งชิดเลนซ้าย ประมาณ 200 เมตร วิ่งตรงเข้ามาจะเห็น RBSC Polo Club เลี้ยวซ้ายตามแนวกำแพง เจอสามแยกเลี้ยวขวา จากนั้นตรงไปสนามฟุตบอลจะอยู่ทางซ้ายมือ
                                </div>
                            </div>
                            <div className=" grid grid-cols-3 md:grid-cols-1 w-full items-center justify-items-center lg:p-8 shadow-sm md:col-start-2 md:col-span-2 min-h-[150px]">
                                <FontAwesomeIcon icon={faTrain} className="w-16 h-16 " />
                                <div className="col-span-2 md:col-span-1">

                                    ลงสถานีรถไฟฟ้าใต้ดินสถานีลุมพินี มุ่งหน้าไปยังทางออกที่ 3 ถนนวิทยุ เรียกมอเตอร์ไซด์รับจ้าง หรือ รถแท็กซี่ ให้มาส่งที่สนามฟุตบอล
                                </div>
                            </div>
                            <div className=" grid grid-cols-3 md:grid-cols-1 w-full items-center justify-items-center lg:p-8 shadow-sm md:col-start-4 md:col-span-2 min-h-[150px]">
                                <FontAwesomeIcon icon={faTrain} className="w-16 h-16 " />
                                <div className="col-span-2 md:col-span-1">

                                    ลงสถานีเพลิตจิต สามารถออกได้ที่ ทางออก 2 อาคารปาร์คเวนเจอร์ หรือ ทางออก 4 ฝั่งโนโวเทล ซอยร่วมฤดี เรียกมอเตอร์ไซด์รับจ้าง หรือ รถแท็กซี่ ให้มาส่งที่สนามฟุตบอล
                                </div>
                            </div>

                        </div>

                    </section>

                    {/* GGmap */}
                    <section className="bg-white h-full w-full relative flex  justify-center items-center min-h-[400px] ">
                        <img src="/assets/map.png" alt="map" className="object-cover w-full h-full object-center absolute" />
                        <div className="h-auto absolute bg-[#08250D] w-full bottom-0 bg-opacity-80 flex justify-center">
                            <div className="max-w-7xl w-full h-full flex justify-center p-4">
                                <div className="w-full relative mx-4 md:mx-8 h-full flex justify-center items-center">
                                    <div className="grid gap-3 grid-cols-1 md:grid-cols-3 divide-y-2 md:divide-x-2 md:divide-y-0  divide-[#B6A694] w-1/2 md:w-full">
                                        <button className="text-white text-center pt-3">

                                            Google Map
                                        </button>
                                        <button className="text-white text-center  pt-3">
                                            Download Map
                                        </button>
                                        <button className="text-white text-center pt-3">
                                            Get Direction
                                        </button>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>

                    {/* Company */}
                    <section className="w-full h-full px-10">
                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 ">
                            <div className="w-full h-full  relative overflow-hidden">
                                <img src="/assets/polo_map.png" alt="map" className="object-cover object-center w-full h-full hover:scale-110 transition-transform duration-100 " />
                            </div>
                            <div className="flex h-full w-full  justify-center flex-col ">
                                <p> บริษัท สยามสินธร จำกัด</p>
                                <p>130-132 อาคารสินธร ทาวเวอร์ 1 ชั้น 4 ถนนวิทยุ แขวงลุมพินี เขตปทุมวัน กรุงเทพฯ 10330</p>
                                <p>จองสนาม : 08-7070-8833</p>
                                <p>จองอีเว้นท์ : 092-270-0241</p>
                                <p>02-263-2525</p>
                                <p>info@polofootballpark.com</p>
                                <p>www.polofootballpark.com</p>
                                <p>PoloFootballPark</p>
                                <p>polo_football_park</p>
                                <p>Line@</p>
                            </div>

                        </div>
                    </section>
                </div>
            </div>
        </Layout>
    );
}

export default Contact;