import Head from "next/head";
import Layout from "../components/Layout";
import Link from 'next/link';
import React, { useState, useEffect } from "react";
import { useRouter } from "next/router";
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faCar, faTrain, faLocationDot, faPhone, faEnvelope, faGlobe } from '@fortawesome/free-solid-svg-icons'
import { faFacebook, faInstagram, faLine } from '@fortawesome/free-brands-svg-icons'
import en from '../locales/en'
import th from '../locales/th'

const Contact = () => {

    const router = useRouter();
    const { locale } = router;
    const t = locale === 'en' ? en : th;

    const changeLanguage = (e) => {
        const locale = e.target.value;
        router.push(router.pathname, router.asPath, { locale });
    };


    return (
        <Layout>
            <Head>
                <title>Contact - Polo Football Park</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="h-full w-full flex justify-center relative ">

                <div className="w-full h-full bg-white md:rounded-tr-[100px]  max-w-7xl  py-10 relative ">
                    <div className="absolute -top-5 -left-8  hidden md:block z-10">
                        <img src="http://upload.wikimedia.org/wikipedia/en/e/ec/Soccer_ball.svg" alt="ball" className="w-24 h-24 roll" />
                    </div>
                    {/* Heading */}
                    <section className="flex w-full flex-col justify-center items-center px-4 lg:px-10">
                        <div className="md:hidden text-center">

                            <p className="text-3xl font-medium"> Contact</p>
                            <p>Get in touch with us!</p>
                        </div>


                        <div className="py-10 grid grid-cols-1 md:grid-cols-6 gap-3 w-full  ">

                            {t.contact.directionByCar
                                .map((item, index) => (
                                    <div key={index} className=" grid grid-cols-3 md:grid-cols-1 w-full items-center justify-items-center lg:p-8 shadow-sm md:col-span-2 min-h-[150px]">
                                        <FontAwesomeIcon icon={faCar} className="w-16 h-16 " />
                                        <div className="col-span-2 md:col-span-1 tracking-normal font-light">
                                            {item.description}
                                        </div>
                                    </div>
                                ))
                            }

                            {t.contact.directionByMRT
                                .map((item, index) => (
                                    <div key={index} className="grid grid-cols-3 md:grid-cols-1 w-full items-center justify-items-center lg:p-8 shadow-sm md:col-start-2 md:col-span-2 min-h-[150px]">
                                        <FontAwesomeIcon icon={faTrain} className="w-16 h-16 " />
                                        <div className="col-span-2 md:col-span-1 tracking-normal font-light ">
                                            {item.description}
                                        </div>
                                    </div>
                                ))
                            }

                            {t.contact.directionByBTS
                                .map((item, index) => (
                                    <div key={index} className="grid grid-cols-3 md:grid-cols-1 w-full items-center justify-items-center lg:p-8 shadow-sm md:col-start-4 md:col-span-2 min-h-[150px]">
                                        <FontAwesomeIcon icon={faTrain} className="w-16 h-16 " />
                                        <div className="col-span-2 md:col-span-1 tracking-normal font-light">
                                            {item.description}
                                        </div>
                                    </div>
                                ))
                            }



                        </div>

                    </section>

                    {/* GGmap */}
                    <section className="bg-white h-full w-full relative flex  justify-center items-center min-h-[400px] ">
                        <img src="/assets/map.png" alt="map" className="object-cover w-full h-full object-center absolute" />
                        <div className="h-auto absolute bg-[#08250D] w-full bottom-0 bg-opacity-80 flex justify-center">
                            <div className="max-w-7xl w-full h-full flex justify-center p-4">
                                <div className="w-full relative mx-4 md:mx-8 h-full flex justify-center items-center">
                                    <div className="grid gap-3 grid-cols-1 md:grid-cols-3 divide-y-2 md:divide-x-2 md:divide-y-0  divide-[#B6A694] w-1/2 md:w-full">
                                        <button className="text-white text-center pt-3">

                                            Google Map
                                        </button>
                                        <button className="text-white text-center  pt-3">
                                            Download Map
                                        </button>
                                        <button className="text-white text-center pt-3">
                                            Get Direction
                                        </button>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>

                    {/* Company */}
                    <section className="w-full h-full px-4 lg:px-10">
                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 ">
                            <div className="w-full h-full  relative overflow-hidden">
                                <img src="/assets/polo_map.png" alt="map" className="object-cover object-center w-full h-full hover:scale-110 transition-transform duration-100 " />
                            </div>
                            <div className="flex h-full w-full  justify-center flex-col ">

                                <p className="text-xl"> {t.contact.companyName} </p>
                                <p className="text-sm whitespace-pre-line font-light xs:text-base inline-flex items-center mt-4">
                                    <FontAwesomeIcon icon={faLocationDot} className="w-8 h-8 mr-4" />
                                    {t.contact.companyAddress}</p>
                                <p className="text-sm whitespace-pre-line font-light xs:text-base inline-flex items-center mt-4">
                                    <FontAwesomeIcon icon={faPhone} className="w-8 h-8 mr-4" />
                                    {t.contact.companyPhone}</p>

                                <p className="text-sm whitespace-pre-line font-light xs:text-base inline-flex items-center mt-4">
                                    <FontAwesomeIcon icon={faEnvelope} className="w-5 h-5 mr-4" />
                                    {t.contact.companyEmail}</p>

                                <p className="text-sm whitespace-pre-line font-light xs:text-base inline-flex items-center mt-2">
                                    <FontAwesomeIcon icon={faGlobe} className="w-5 h-5 mr-4" />
                                    {t.contact.companySite}</p>
                                <p className="text-sm whitespace-pre-line font-light xs:text-base inline-flex items-center mt-2">
                                    <FontAwesomeIcon icon={faFacebook} className="w-5 h-5 mr-4" />
                                    {t.contact.companyfacebook}</p>
                                <p className="text-sm whitespace-pre-line font-light xs:text-base inline-flex items-center mt-2">
                                    <FontAwesomeIcon icon={faInstagram} className="w-5 h-5 mr-4" />
                                    {t.contact.companyIg}</p>
                                <p className="text-sm whitespace-pre-line font-light xs:text-base inline-flex items-center mt-2">
                                    <FontAwesomeIcon icon={faLine} className="w-5 h-5 mr-4" />
                                    {t.contact.companyLine}</p>


                            </div>

                        </div>
                    </section>
                </div>
            </div>
        </Layout>
    );
}

export default Contact;