import Head from "next/head";
import Layout from "../components/Layout";
import Link from 'next/link';
import React, { useState, useEffect } from "react";
import { useRouter } from "next/router";
import '@fancyapps/ui/dist/carousel.css';

const CookiesPolicy = () => {

    return (
        <Layout>
            <Head>
                <title>Cookies Policy - Polo Football Park</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="h-full w-full relative flex justify-center">
                <div className="w-full h-full bg-white md:rounded-tr-[100px]  max-w-7xl  py-10 relative ">
                    <div className="absolute -top-5 -left-8  hidden md:block z-10">
                        <img src="/assets/Soccer_ball.svg" alt="ball" className="w-24 h-24 roll" />
                    </div>
                    <section className="flex w-full flex-col justify-center items-center px-4 lg:px-10 ">
                        <p className="text-3xl font-medium md:hiiden">​​​​​​​​​​​​​นโยบายการใช้คุกกี้ Cookies Policy</p>

                        <div className="font-light my-10">

                            <p className="whitespace-pre-line">
                                บริษัท สยามสินธร จำกัด อาจมีการใช้คุกกี้หรือเทคโนโลยีอื่นใดที่มีลักษณะใกล้เคียงกัน (“คุกกี้”) บนเว็บไซต์ เพื่อช่วยให้คุณได้รับประสบการณ์ที่ดีจากการใช้บริการและช่วยให้บริษัทสามารถพัฒนาคุณภาพของบริการให้ตอบสนองต่อความต้องการของคุณมากยิ่งขึ้น
                            </p>
                            <br></br>
                            <p >
                                <span className="font-normal text-lg">ประโยชน์ของคุกกี้ </span><br></br>
                                คุกกี้ช่วยให้บริษัททราบว่าคุณเข้าชมส่วนใดในเว็บไซต์และ/หรือแอปพลิเคชันของบริษัทเพื่อที่บริษัทจะสามารถมอบประสบการณ์การใช้บริการที่ดีขึ้นและตรงกับความต้องการของคุณและช่วยให้คุณสามารถใช้บริการเว็บไซต์และ/หรือแอปพลิเคชันของบริษัทได้อย่างต่อเนื่อง นอกจากนี้การบันทึกการตั้งค่าแรกของบริการด้วยคุกกี้จะช่วยให้คุณเข้าถึงบริการด้วยค่าที่ตั้งไว้ทุกครั้งที่ใช้งาน ยกเว้นในกรณีที่คุกกี้ถูกลบซึ่งจะทำให้การตั้งค่าทุกอย่างจะกลับไปที่ค่าเริ่มต้น
                            </p>
                            <br></br>
                            <p>
                                <span className="font-normal text-lg"> ประเภทของคุกกี้ที่ใช้ </span><br></br>

                                ประเภทของคุกกี้ที่บริษัทใช้รวมถึงแต่ไม่จำกัดเฉพาะรายการต่อไปนี้
                            </p>

                            <div className=" grid grid-cols-3  my-4 justify-items-center border-separate border-b border-r divide-x divide-y">
                                <div className="bg-[#08250D] text-white w-full h-full flex justify-center items-center border-l border-t p-3">
                                    ประเภทของคุกกี้
                                </div>
                                <div className="bg-[#08250D] text-white w-full h-full flex justify-center items-center p-3">
                                    รายละเอียด
                                </div>
                                <div className="bg-[#08250D] text-white w-full h-full flex justify-center items-center p-3">
                                    ตัวอย่าง
                                </div>
                                <div className="w-full h-full flex justify-center items-center p-3">
                                    คุกกี้ประเภทจำเป็นถาวร(Strictly Necessary cookies)
                                </div>
                                <div className="w-full h-full flex justify-center items-center p-3">
                                    คุกกี้ประเภทนี้จำเป็นสำหรับการทำงานของเว็บไซต์และ/หรือแอปพลิเคชันของบริษัทเพื่อช่วยให้คุณสามารถเข้าถึงข้อมูลและใช้เว็บไซต์และ/หรือแอปพลิเคชันของธนาคารได้อย่างปลอดภัย จึงไม่สามารถปิดการใช้คุกกี้ประเภทนี้ได้
                                </div>
                                <div className="w-full h-full flex justify-center items-center p-3">
                                    <ul>
                                        <li>SessionID</li>
                                        <li>​Load Balancing</li>
                                        <li>User ID</li>
                                        <li>Security</li>
                                    </ul>
                                </div>
                                <div className="w-full h-full flex justify-center items-center text-center p-3">
                                    คุกกี้ประเภทการวิเคราะห์ และวัดผลการทำงาน
                                    (Analytic/Performance cookie)
                                </div>
                                <div className="w-full h-full flex justify-center items-center p-3">
                                    คุกกี้ประเภทนี้ช่วยให้ธนาคารสามารถวิเคราะห์หรือวัดผลการทำงาน เพื่อให้ธนาคารเข้าใจถึงความสนใจของคุณ เช่น การประมวลผลจำนวนผู้เยี่ยมชมเว็บไซต์และ/หรือแอปพลิเคชันของบริษัทพฤติกรรมการเยี่ยมชมเว็บไซต์และ/หรือแอปพลิเคชันของบริษัทจำนวนหน้าที่คุณเข้าใช้งาน โดยธนาคารจะใช้ข้อมูลดังกล่าวในการปรับปรุงและพัฒนาประสิทธิภาพการทำงานของเว็บไซต์และ/หรือแอปพลิเคชันของบริษัทให้ตอบสนองตามความต้องการและการใช้งานของคุณให้ดียิ่งขึ้น
                                </div>
                                <div className="w-full h-full flex justify-center items-center p-3">
                                    <ul>
                                        <li>Google Analytics</li>
                                        <li>​Adobe​</li>

                                    </ul>
                                </div>

                                <div className="w-full h-full flex justify-center items-center p-3">
                                    คุกกี้ประเภทการโฆษณา
                                    (advertising cookies)
                                </div>
                                <div className="w-full h-full flex justify-center items-center p-3">
                                    คุกกี้ประเภทนี้จะถูกบันทึกบนอุปกรณ์ของคุณเพื่อเก็บข้อมูลการเข้าใช้งานและลิงก์ที่คุณติดตามหรือเยี่ยมชม เพื่อให้เข้าใจความต้องการของคุณและใช้ในการ นำเสนอสิทธิประโยชน์ ประชาสัมพันธ์ โฆษณา ให้เหมาะสมกับความสนใจของคุณมากที่สุด
                                </div>
                                <div className="w-full h-full flex justify-center items-center p-3">
                                    <ul>
                                        <li>Adobe Audience Manager</li>
                                        <li>Adobe Target</li>
                                        <li>Google Analytics</li>
                                        <li>Facebook Pixels</li>
                                        <li>Facebook API</li>

                                    </ul>
                                </div>
                                <div className="w-full h-full flex justify-center items-center p-3">
                                    คุกกี้ประเภทการทำงาน
                                    (Functional cookies)
                                </div>
                                <div className="w-full h-full flex justify-center items-center p-3">
                                    คุกกี้ประเภทนี้จะช่วยให้บริษัท“จดจำ” คุณระหว่างการเยี่ยมชมและตั้งค่าเว็บไซต์และ/หรือแอปพลิเคชันของบริษัทตามลักษณะการใช้งานให้สอดคล้องกับสิ่งที่คุณเลือกเพื่ออำนวยความสะดวกเมื่อคุณกลับเข้ามาใช้เว็บไซต์และ/หรือแอปพลิเคชันของบริษัทในครั้งถัดไป เช่น การจดจำชื่อผู้ใช้งานของคุณ การปรับขนาดตัวอักษร ภาษาและส่วนอื่นๆ บนหน้าเว็บไซต์และ/หรือแอปพลิเคชันของธนาคาร
                                </div>
                                <div className="w-full h-full flex justify-center items-center p-3">
                                    <ul>
                                        <li>Google Analytics</li>
                                        <li>SessionID</li>


                                    </ul>
                                </div>


                            </div>
                            <p>ในกรณีที่มีการเชื่อมโยงกับแพลตฟอร์มของบุคคลที่สาม เช่น เครือข่ายการโฆษณา สื่อสังคมออนไลน์ ผู้ให้บริการเว็บไซต์ภายนอกอื่นๆ เป็นต้น คุกกี้บางประเภทอาจมีการจัดการโดยบุคคลที่สาม จึงแนะนำให้คุณศึกษาและทำความเข้าใจนโยบายการใช้คุกกี้และนโยบายการคุ้มครองข้อมูลส่วนบุคคลของบุคคลที่สามด้วย</p>
                            <br></br>

                            <p>
                                <span className="font-normal text-lg">การตั้งค่าและการปฏิเสธคุกกี้ </span><br></br>
                                คุณสามารถเลือกปฏิเสธการทำงานของคุกกี้ได้ตามความต้องการของคุณโดยการตั้งค่าเบราว์เซอร์หรือการตั้งค่าความเป็นส่วนตัวของคุณ เพื่อระงับการเก็บรวบรวมข้อมูลโดยคุกกี้ในอนาคตอย่างไรก็ตามหากคุณตั้งค่าเบราว์เซอร์หรือค่าความเป็นส่วนตัวของคุณด้วยการปฏิเสธการทำงานของคุกกี้ทั้งหมดคุณอาจไม่สามารถใช้งานฟังก์ชั่นบางอย่างหรือทั้งหมดบนเว็บไซต์และหรือแvปพลิเคชันของบริษัทได้อย่างมีประสิทธิภาพ ทั้งนี้ คุณสามารถศึกษารายละเอียดเพิ่มเติมได้จาก
                                <a href=" www.allaboutcookies.org​" className="text-green-500"> www.allaboutcookies.org​</a>
                            </p>
                            <br></br>

                            <p>
                                <span className="font-normal text-lg">การเปลี่ยนแปลงนโยบาย </span><br></br>
                                นโยบายการใช้คุกกี้นี้อาจมีการปรับปรุงแก้ไขหรือเปลี่ยนแปลงตามความเหมาะสมเพื่อให้เป็นไปตามกฎหมายและกฎระเบียบที่เกี่ยวข้อง บริษัทจึงขอแนะนำให้คุณตรวจสอบเพื่อให้แน่ใจว่าคุณเข้าใจการเปลี่ยนแปลงนโยบายดังกล่าว ทั้งนี้คุณสามารถดูข้อมูลเพิ่มเติมเกี่ยวกับการเก็บรวบรวม ใช้ และเปิดเผยข้อมูลส่วนบุคคลของคุณ สิทธิต่างๆ รวมถึงรายละเอียดเกี่ยวกับผู้ควบคุมข้อมูลส่วนบุคคลได้จากนโยบายการคุ้มครองข้อมูลส่วนบุคคลของบริษัทบนเว็บไซต์
                                <a href="www.xxxxxx.com/th/privacy-policy" className="text-green-500">  (www.xxxxxx.com/th/privacy-policy)</a>
                            </p>
                            <br></br>

                            <p className="whitespace-pre-line">
                                <span className="font-normal text-lg"> คุณสามารถจัดการคุกกี้ในเบราว์เซอร์ของท่านได้โดยการตั้งค่า ดังนี้ </span><br></br><br></br>

                                Cookies settings in Chrome <a href="https://support.google.com/chrome/answer/95647?hl=en&ref_topic=14666" className="text-green-500"> (https://support.google.com/chrome/answer/95647?hl=en&ref_topic=14666)</a>
                                <br></br><br></br>

                                Cookies settings in Firefox
                                <a href="https://support.mozilla.org/en-US/kb/cookies-information-websites-store-on-your-computer?redirectlocale=en-US&redirectslug=Cookies" className="text-green-500"> (https://support.mozilla.org/en-US/kb/cookies-information-websites-store-on-your-computer?redirectlocale=en-US&redirectslug=Cookies)</a>


                                <br></br><br></br>
                                Cookies settings in Safari
                                <a href="https://support.apple.com/guide/safari/manage-cookies-and-website-data-sfri11471/mac" className="text-green-500"> (https://support.apple.com/guide/safari/manage-cookies-and-website-data-sfri11471/mac)</a>
                                and iOS
                                <a href="https://support.apple.com/en-us/HT201265" className="text-green-500"> (https://support.apple.com/en-us/HT201265)</a>

                                <br></br><br></br>

                                Cookies settings in Internet Explorer
                                <a href="https://support.microsoft.com/en-us/topic/delete-and-manage-cookies-168dab11-0753-043d-7c16-ede5947fc64d#ie=ie-10" className="text-green-500"> (https://support.microsoft.com/en-us/topic/delete-and-manage-cookies-168dab11-0753-043d-7c16-ede5947fc64d#ie=ie-10)</a>

                            </p>
                        </div>


                    </section>

                </div>



            </div>
        </Layout>
    );
}

export default CookiesPolicy;