import Head from "next/head";
import Layout from "../components/Layout";
import Link from 'next/link';
import React, { useState, useEffect } from "react";
import { useRouter } from "next/router";
import '@fancyapps/ui/dist/carousel.css';

const CookiesPolicy = () => {

    return (
        <Layout>
            <Head>
                <title>Cookies Policy - Polo Football Park</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="h-full  w-full relative flex justify-center">
                <div className="min-h-screen w-full h-full bg-white md:rounded-tr-[100px]  max-w-7xl  py-10 relative ">
                    <div className="absolute -top-5 -left-8  hidden md:block z-10">
                        <img src="/assets/Soccer_ball.svg" alt="ball" className="w-24 h-24 roll" />
                    </div>
                    <section className="flex w-full min-h-screen h-full flex-col justify-center items-center px-4 lg:px-10">
                        <h1 className="text-center text-4xl">Under Development</h1>


                    </section>

                </div>



            </div>
        </Layout>
    );
}

export default CookiesPolicy;