import Head from "next/head";
import Layout from "../components/Layout";
import Link from 'next/link';
import React, { useState, useEffect } from "react";
import { useRouter } from "next/router";
import '@fancyapps/ui/dist/carousel.css';

const News = () => {

    return (
        <Layout>
            <Head>
                <title>News&Event - Polo Football Park</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="h-full w-full relative flex justify-center">
                <div className="w-full h-full bg-white md:rounded-tr-[100px]  max-w-7xl  py-10 relative ">
                    <div className="absolute -top-5 -left-8  hidden md:block z-10">
                        <img src="http://upload.wikimedia.org/wikipedia/en/e/ec/Soccer_ball.svg" alt="ball" className="w-24 h-24 roll" />
                    </div>
                    <section className="flex w-full flex-col justify-center items-center px-4 lg:px-10">
                        <p className="text-3xl font-medium">News&Event</p>
                        {/* Highlight */}
                        <div className="grid grid-cols-1 sm:grid-cols-3 sm:grid-rows-2 w-full h-full gap-3 mt-10 ">
                            <div className="sm:row-span-2 w-full h-full bg-black sm:col-span-2">
                                <img src="https://polofootballpark.com//images/gallery/756bdad4eca19d3c2db070078fa7602a_80676db8f32b521cf13f39219b9f6581-1458615514.jpg" alt="feed1" className="object-cover w-full h-full" />
                            </div>
                            <div>
                                <img src="https://polofootballpark.com//images/gallery/756bdad4eca19d3c2db070078fa7602a_80676db8f32b521cf13f39219b9f6581-1458615514.jpg" alt="feed4" className="object-cover w-full h-full" />
                            </div>
                            <div>
                                <img src="https://polofootballpark.com//images/gallery/756bdad4eca19d3c2db070078fa7602a_80676db8f32b521cf13f39219b9f6581-1458615514.jpg" alt="feed3" className="object-cover w-full h-full" />
                            </div>
                        </div>

                        {/* News from facebook */}
                        <div className="my-10 w-full h-full ">
                            <p className="text-2xl font-medium">Hot</p>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-5 ">
                                <div className=" grid grid-cols-1 sm:grid-cols-3 shadow-sm  sm:h-[200px] h-full">
                                    <div className="w-full h-full overflow-hidden">
                                        <img src="https://scontent.fbkk14-1.fna.fbcdn.net/v/t39.30808-6/277749427_371398074993076_8684052199350618991_n.jpg?_nc_cat=101&ccb=1-5&_nc_sid=730e14&_nc_ohc=wcaD01H09WcAX_BG1vC&_nc_ht=scontent.fbkk14-1.fna&oh=00_AT9UzCYMwW-Us3y1cE7xyQTbH2lpKxa3x-9cCFS2AOzMHg&oe=62666307" alt="facebook" className="object-cover object-center w-full h-full max-h-96" />
                                    </div>
                                    <div className="sm:col-span-2 px-5 h-full flex flex-col justify-center ">

                                        โปรพิเศษสำหรับ นักเรียน / นักศึกษา มาแล้วคร้า..รีบมากันนะคะ
                                        <div>

                                            <button className="">Read more</button>
                                        </div>
                                        <div className="">
                                            30 มีนาคม 2565
                                        </div>
                                    </div>
                                </div>
                                <div className=" grid grid-cols-1 sm:grid-cols-3 shadow-sm  sm:max-h-[200px] h-full">
                                    <div className="w-full h-full overflow-hidden">
                                        <img src="https://scontent.fbkk14-1.fna.fbcdn.net/v/t39.30808-6/276214834_7465462490145705_8714022255787854411_n.jpg?_nc_cat=104&ccb=1-5&_nc_sid=8bfeb9&_nc_ohc=NH3cmvqlri4AX_o6Tph&_nc_ht=scontent.fbkk14-1.fna&oh=00_AT_63C77hO-tWkMBMIV-wCbNH5t-y6sY6eSj3-KQn9bw7w&oe=6266D384" alt="facebook" className="object-cover w-full h-full object-center max-h-96" />
                                    </div>
                                    <div className="sm:col-span-2 px-5 h-full flex flex-col justify-center ">

                                        ⚽️ Sunday Morning Training! ⚽️
                                        9:00-10:00@Polo Football Park
                                        Our new Sunday morning sessions are great fun for all ages
                                        <div>

                                            <button className="">Read more</button>
                                        </div>
                                        <div className="">
                                            30 มีนาคม 2565
                                        </div>
                                    </div>
                                </div>
                                <div className=" grid grid-cols-1 sm:grid-cols-3 shadow-sm  sm:max-h-[200px] h-full">
                                    <div className="w-full h-full overflow-hidden">
                                        <img src="https://scontent.fbkk10-1.fna.fbcdn.net/v/t39.30808-6/275054434_351085487024335_8624707730743307175_n.jpg?stp=dst-jpg_p180x540&_nc_cat=109&ccb=1-5&_nc_sid=8bfeb9&_nc_ohc=GY80WRKlisUAX8SMVO_&_nc_ht=scontent.fbkk10-1.fna&oh=00_AT-dLDeXL803hlgWpbjNsHOvgpLzYZ_piseRwd-bmz_lkA&oe=6267B04E" alt="facebook" className="object-cover w-full h-full object-center max-h-96" />
                                    </div>
                                    <div className="sm:col-span-2 px-5 h-full flex flex-col justify-center">

                                        ถามหากันเยอะ..มาแล้วคร้าาา..โปรโมชั่น..เดือนนี้นะคะ
                                        <div>

                                            <button className="">Read more</button>
                                        </div>
                                        <div className="">
                                            30 มีนาคม 2565
                                        </div>
                                    </div>
                                </div>
                                <div className=" grid grid-cols-1 sm:grid-cols-3 shadow-sm  sm:max-h-[200px] h-full">
                                    <div className="w-full h-full overflow-hidden">
                                        <img src="https://scontent.fbkk10-1.fna.fbcdn.net/v/t39.30808-6/271736384_5307191989310888_6530339966365474160_n.jpg?stp=dst-jpg_s640x640&_nc_cat=102&ccb=1-5&_nc_sid=730e14&_nc_ohc=qLOvVwEgcosAX86DOUu&_nc_ht=scontent.fbkk10-1.fna&oh=00_AT_sJkLDQVFvM09RXcXVikRe3QyhqZTPTTH73qAbn_rVGg&oe=626724E7" alt="facebook" className="object-cover w-full h-full object-center max-h-96" />
                                    </div>
                                    <div className="sm:col-span-2 px-5 h-full flex flex-col justify-center ">

                                        ⚽️อุปกรณ์พร้อมมาเล่นฟุตบอลกันค่ะ⚽️⚽️สนใจจองประจำ ⚽️
                                        สอบถามละเอียดเพิ่มเติ่มได้ที่☎️☎️ 087-0708833 , 092-2700241
                                        <div>

                                            <button className="">Read more</button>
                                        </div>
                                        <div className="">
                                            30 มีนาคม 2565
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </section>

                </div>



            </div>
        </Layout>
    );
}

export default News;