import Head from "next/head";
import Layout from "../../components/Layout";
import Link from 'next/link';
import React, { useState, useEffect } from "react";
import { useRouter } from "next/router";
import '@fancyapps/ui/dist/carousel.css';

import en from '../../locales/en'
import th from '../../locales/th'


const Corner = () => {
    const router = useRouter();
    const { locale } = router;
    const t = locale === 'en' ? en : th;

    const changeLanguage = (e) => {
        const locale = e.target.value;
        router.push(router.pathname, router.asPath, { locale });
    };
    return (
        <Layout>
            <Head>
                <title>Corner - Polo Football Park</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="h-full w-full  flex justify-center">
                <div className="min-h-screen w-full h-full bg-white md:rounded-tr-[100px]  max-w-7xl  py-10 relative ">
                    <div className="absolute -top-5 -left-8  hidden md:block z-10">
                        <img src="http://upload.wikimedia.org/wikipedia/en/e/ec/Soccer_ball.svg" alt="ball" className="w-24 h-24 roll" />
                    </div>
                    <section className="flex w-full flex-col justify-center items-center px-4 lg:px-10">
                        <p className="text-3xl font-medium md:hidden">Polo Corner</p>

                        <div className="grid  grid-cols-1 md:grid-cols-2 gap-3 w-full my-5 md:my-10">
                            {t.corner.map((item, index) => (
                                <div key={index} className="grid grid-cols-1 sm:grid-cols-2 gap-3 justify-items-center w-full">
                                    <div className=" w-full">
                                        <img src={item.img} alt="profile" className="object-cover w-full h-full" />
                                    </div>
                                    <div className=" w-full gap-1 flex flex-col ">

                                        <p className="font-semibold text-xl"> {item.topic} </p>
                                        <p className="text-base text-slate-400 font-light !m-0">{item.date}</p>
                                        <p className="text-sm sm:text-base font-light"> {item.content.replace(/(<([^>]+)>)/gi, "").slice(0, 160).concat('...')} </p>

                                        <Link href={item.slug}>
                                            <button className="border-black border-2 px-2 w-fit font-light">
                                                {locale === "en" ? "Read more" : "อ่านเพิ่มเติม"}
                                            </button>
                                        </Link>

                                    </div>
                                </div>
                            ))

                            }

                        </div>

                    </section>

                </div>



            </div>
        </Layout>
    );
}

export default Corner;