import Head from "next/head";
import Layout from "../../components/Layout";
import Link from 'next/link';
import React, { useState, useEffect } from "react";
import { useRouter } from "next/router";
import '@fancyapps/ui/dist/carousel.css';

const Corner = () => {

    return (
        <Layout>
            <Head>
                <title>Corner - Polo Football Park</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="h-full w-full  flex justify-center">
                <div className="min-h-screen w-full h-full bg-white md:rounded-tr-[100px]  max-w-7xl  py-10 relative ">
                    <div className="absolute -top-5 -left-8  hidden md:block z-10">
                        <img src="http://upload.wikimedia.org/wikipedia/en/e/ec/Soccer_ball.svg" alt="ball" className="w-24 h-24 roll" />
                    </div>
                    <section className="flex w-full flex-col justify-center items-center px-4 lg:px-10">
                        <p className="text-3xl font-medium">Polo Corner</p>

                        <div className="grid  grid-cols-1 md:grid-cols-2 gap-3 w-full my-10">
                            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 justify-items-center w-full">
                                <div className=" w-full">
                                    <img src="https://polofootballpark.com/images/post/e7d053b893d547383895457cf582579f-1463371734.jpg" alt="xxxx" className="object-cover w-full h-full" />
                                </div>
                                <div className=" w-full gap-2 flex flex-col ">
                                    <p className="font-semibold text-xl">Lorem ipsum dolor sit amet.<br></br>
                                        <span className="text-base text-slate-400 font-normal">10 April 2022</span>
                                    </p>
                                    <p> Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reiciendis exercitationem harum soluta eum similique perspiciatis repellat fugit </p>
                                    <Link href="/corner/1">

                                        <button className="border-black border-2 p-1 w-fit">
                                            Read more
                                        </button>
                                    </Link>

                                </div>
                            </div>
                            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 justify-items-center w-full">
                                <div className=" w-full">
                                    <img src="https://polofootballpark.com/images/post/74eb2d59fda742e6dba6c570b8531e4b-1465548367.jpg" alt="xxxx" className="object-cover w-full h-full" />
                                </div>
                                <div className=" w-full gap-2 flex flex-col ">
                                    <p className="font-semibold text-xl">Lorem ipsum dolor sit amet.<br></br>
                                        <span className="text-base text-slate-400 font-normal">10 April 2022</span>
                                    </p>
                                    <p> Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reiciendis exercitationem harum soluta eum similique perspiciatis repellat fugit </p>
                                    <Link href="/corner/2">

                                        <button className="border-black border-2 p-1 w-fit">
                                            Read more
                                        </button>
                                    </Link>

                                </div>
                            </div>

                        </div>

                    </section>

                </div>



            </div>
        </Layout>
    );
}

export default Corner;